# Generated by Django 3.1.3 on 2025-11-27 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('category', models.CharField(choices=[('ALL', '전체'), ('BREAD', '빵'), ('BEVERAGE', '음료수'), ('CAKE', '케이크')], max_length=20)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)])),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField(max_length=1000)),
                ('inputdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
