# Generated by Django 3.1.3 on 2025-11-26 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('role', models.CharField(choices=[('USER', '일반 회원'), ('ADMIN', '관리자')], default='USER', max_length=10)),
                ('regdate', models.DateField(default=django.utils.timezone.now, verbose_name='등록 일자')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
