# Generated by Django 3.1.3 on 2025-11-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
